In [36]:
#------------>Section A: Data Structures & Control Structures

In [1]:
# 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.
a=[50,6,79,77,35]
a

[50, 6, 79, 77, 35]

In [2]:
type(a) # creating list

list

In [3]:
a.append(89) #using adding eliment in to the list
a

[50, 6, 79, 77, 35, 89]

In [4]:
b=[10,15]
a.extend(b) # take b list extend the list to a
a

[50, 6, 79, 77, 35, 89, 10, 15]

In [5]:
a.insert(3,100) # insert the eliment in to the list in 3rd place
a

[50, 6, 79, 100, 77, 35, 89, 10, 15]

In [6]:
a.remove(79) # removing eliment into the list
a

[50, 6, 100, 77, 35, 89, 10, 15]

In [7]:
a.pop(6) # pop the 6 eliment into the list 
a

[50, 6, 100, 77, 35, 89, 15]

In [8]:
k= [1, 2, 3, 4, 5] 
print(k)

[1, 2, 3, 4, 5]


In [9]:
k.clear() # clear the k list
print(k)

[]


In [10]:
a.index(100) # 100 contain 2nd place in a list

2

In [11]:
l=[11,23,45,67,77,11,99,45,2,11,100,45,23]
l.count(11) # count the 11 elemint into the list it repeat 3 times

3

In [12]:
a.sort() # sort the list into assending order
a

[6, 15, 35, 50, 77, 89, 100]

In [13]:
a.reverse() # sort the list into decending order
a

[100, 89, 77, 50, 35, 15, 6]

In [16]:
# 2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.
t = ("cow", "dog", "hen")
type(t)

tuple

In [17]:
t[1]="king" # try to chaing the second name in tuple it shows a Error
 #The reason is tuples are immutable data structures 
#Once a tuple is created we cannot modify its elements

TypeError: 'tuple' object does not support item assignment

In [20]:
#3.	Create a set of integers with some duplicate values. Print the set and explain the output.
s = {10, 20, 30, 20, 40, 10, 50}
type(s) #Create a set of integers with intentional duplicates

set

In [21]:
print(s) # Print the set

{50, 20, 40, 10, 30}


In [22]:
#Sets Store Only Unique Elements.
#Sets Are Unordered it means Notice that the printed output is not the same as the input. 
#set do not store elements in a specific sequence.

In [25]:
#4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.
d= {'name': 'Kowshik','age': 24,'city': 'Hyderabad'}
type(d)  #Create a dictionary contain name,age and city

dict

In [26]:
print(d)

{'name': 'Kowshik', 'age': 24, 'city': 'Hyderabad'}


In [27]:
d['age'] = 33 # update the age into dictionary
print(d) 

{'name': 'Kowshik', 'age': 33, 'city': 'Hyderabad'}


In [28]:
d['email'] = 'sadulakowshikreddy@gmail.com' # adding new key value email
print(d)

{'name': 'Kowshik', 'age': 33, 'city': 'Hyderabad', 'email': 'sadulakowshikreddy@gmail.com'}


In [31]:
# 5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.
age=24      # taking age as varable
age 

24

In [32]:
if age >= 18: # by using if-else statement printing person is eligible for voting or not.
        print("eligible for voting")
else:
    print("not eligible")

eligible for voting


In [34]:
#6.	Given a 'marks' variable, print the grade:
#- 90 and above: 'A'
#- 75–89: 'B'
#- 50–74: 'C'
#- Below 50: 'Fail'


marks = 67
if marks < 0 or marks > 100:       # marks is not between 0-100 outside the range
    print("The marks are outside the range(0-100).")
elif marks >= 90 and marks<=100:    # 90 and above: 'A'
   print( "grade is:-",'A')
elif marks >= 75 and marks<=89:     # 75–89: 'B'
    print( "grade is:-",'B')
elif marks >= 50 and marks<=74:      # 50–74: 'C'
    print( "grade is:-",'C')
else:                                 # else  Below 50: 'Fail'
    print( "grade is:-",'Fail')

grade is:- C


In [39]:
#7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.


number = 10
if number > 0:
    if number % 2 == 0:         # number is grater than 0 if it is even-number means print even-number
        print("Even Number.")
    elif number == 0:           # If the number is zero
        print("Zero.")
    else:
       print("Odd Number.")     # number is grater than 0 if it is Odd-number means print Odd-number
else:                           # number is less than 0 printing negative number
    print( "Negative Number.")
    

Even Number.


In [ ]:
#-------------------->Section B: Numpy

In [40]:
# 8.	Create:
#- A scalar using np.array(5)
#- A 1D array with values 1 to 5
#- A 2D array (2x3) with values from 10 to 60 in steps of 10
import numpy as np


In [41]:
scalar_value = np.array(5)
print (scalar_value)

5


In [42]:
type(scalar_value)

numpy.ndarray

In [43]:
A= [1, 2, 3, 4, 5] # 1D array with value 1-5
print(A)

[1, 2, 3, 4, 5]


In [45]:
A2= [[10, 20, 30],[40, 50, 60]] # 2D array with value 10-60
A2

[[10, 20, 30], [40, 50, 60]]

In [46]:
#9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().


data= np.random.randint(0, 100, size=(4, 4))

In [47]:
print(data)

[[67  7  6 15]
 [91 70 52 81]
 [65 84 23 10]
 [42 65 83 35]]


In [49]:
# 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.


import numpy as np     
data= np.array([[11, 42, 63],[44, 35, 6],[87, 18, 59]]) # Create a 2D numpy array of shape (3x3)
data

array([[11, 42, 63],
       [44, 35,  6],
       [87, 18, 59]])

In [50]:
import pandas as pd
df = pd.DataFrame(numpy_array, columns=['A', 'B', 'C']) # Convert the numpy into pandas DataFrame and add column names
df

,A,B,C
0,11,42,63
1,44,35,6
2,87,18,59


In [ ]:
# ------------------------>Section C: Exploring Pandas

In [51]:
#11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
#- Use .info(), .describe()
#- Select 'Name' and 'City' columns
#- Drop 'City' column
#- Fill any missing values in 'Salary' column with the mean
#- Remove any duplicate rows



import pandas as pd      
import numpy as np



# -Create a DataFrame manually with 10 rows and four columns
data = {
    'Name': ['Alex', 'Bella', 'Chris', 'David', 'Eve', 'Alex', 'Fiona', 'George', 'Hannah', 'Ian'],
    'Age': [25, 30, 22, 45, 35, 25, 28, 33, 40, 27],
    'City': ['London', 'Paris', 'Berlin', 'Rome', 'Madrid', 'London', 'Vienna', 'London', 'Oslo', 'Zurich'],
    # Including two missing values (NaN) in 'Salary' for the imputation step
    'Salary': [50000, 60000, np.nan, 80000, 75000, 50000, 62000, np.nan, 90000, 70000]}

print(data)

{'Name': ['Alex', 'Bella', 'Chris', 'David', 'Eve', 'Alex', 'Fiona', 'George', 'Hannah', 'Ian'], 'Age': [25, 30, 22, 45, 35, 25, 28, 33, 40, 27], 'City': ['London', 'Paris', 'Berlin', 'Rome', 'Madrid', 'London', 'Vienna', 'London', 'Oslo', 'Zurich'], 'Salary': [50000, 60000, nan, 80000, 75000, 50000, 62000, nan, 90000, 70000]}


In [52]:
df = pd.DataFrame(data)
df

,Name,Age,City,Salary
0,Alex,25,London,50000.0
1,Bella,30,Paris,60000.0
2,Chris,22,Berlin,NaN
3,David,45,Rome,80000.0
4,Eve,35,Madrid,75000.0
5,Alex,25,London,50000.0
6,Fiona,28,Vienna,62000.0
7,George,33,London,NaN
8,Hannah,40,Oslo,90000.0
9,Ian,27,Zurich,70000.0


In [53]:
#- info(),.describe()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [54]:
df.describe()

,Age,Salary
count,10.000000,8.000000
mean,31.000000,67125.000000
std,7.272475,14257.203693
min,22.000000,50000.000000
25%,25.500000,57500.000000
50%,29.000000,66000.000000
75%,34.500000,76250.000000
max,45.000000,90000.000000


In [56]:
#-Select 'Name' and 'City' columns
df[['Name', 'City']]

,Name,City
0,Alex,London
1,Bella,Paris
2,Chris,Berlin
3,David,Rome
4,Eve,Madrid
5,Alex,London
6,Fiona,Vienna
7,George,London
8,Hannah,Oslo
9,Ian,Zurich


In [57]:
#- Drop 'City' column
df.drop('City', axis=1)

,Name,Age,Salary
0,Alex,25,50000.0
1,Bella,30,60000.0
2,Chris,22,NaN
3,David,45,80000.0
4,Eve,35,75000.0
5,Alex,25,50000.0
6,Fiona,28,62000.0
7,George,33,NaN
8,Hannah,40,90000.0
9,Ian,27,70000.0


In [58]:
#- Fill any missing values in 'Salary' column with the mean
m=df['Salary'].mean()
print(m)

67125.0


In [59]:
df['Salary'].fillna(value=m, inplace =True)
df

C:\Users\hp 840 g8\AppData\Local\Temp\ipykernel_9424\3357209940.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(value=m, inplace =True)


,Name,Age,City,Salary
0,Alex,25,London,50000.0
1,Bella,30,Paris,60000.0
2,Chris,22,Berlin,67125.0
3,David,45,Rome,80000.0
4,Eve,35,Madrid,75000.0
5,Alex,25,London,50000.0
6,Fiona,28,Vienna,62000.0
7,George,33,London,67125.0
8,Hannah,40,Oslo,90000.0
9,Ian,27,Zurich,70000.0


In [60]:
#- Remove any duplicate rows
df.drop_duplicates(inplace=True)
df

,Name,Age,City,Salary
0,Alex,25,London,50000.0
1,Bella,30,Paris,60000.0
2,Chris,22,Berlin,67125.0
3,David,45,Rome,80000.0
4,Eve,35,Madrid,75000.0
6,Fiona,28,Vienna,62000.0
7,George,33,London,67125.0
8,Hannah,40,Oslo,90000.0
9,Ian,27,Zurich,70000.0
